Minor fixes (~/tom.yaml file) , release! version 0.1.26

diff --git a/sparrow.yaml b/sparrow.yaml
--- a/sparrow.yaml
+++ b/sparrow.yaml
@@ -2,20 +2,78 @@ secrets:
   - FEZ_TOKEN
 
 tasks:
-  -
-    name: tomty
-    language: Bash
-    default: true
-    code: |
-      set -e
-      cd source/
-      zef install . --/test
-      export SP6_LOG_NO_TIMESTAMPS=1
-      tomty  --all --show-failed --color --dump-task
 
+  -
+    name: main
+    default: true
+    language: Raku
+    code: |
+      use Text::Table::Simple;
+      my @columns = ("Rakudo Version", "Status", "Time", "Linux Dist");
+      my @rows;
+      my $fail = False;
+      for config()<tasks><multi-versions><state><list><> -> $i {
+        @rows.push: [ $i<version>, $i<status>,  $i<time>, os() ];
+        $fail = True unless $i<status> eq "OK";
+      }
+      my @table = lol2table(@columns,@rows);
+      .say for @table;
+      die "some tests failed" if $fail == True;
+    depends:
+      -
+        name: test-versions
     followup:
       -
         name: release
+  -
+    name: test-versions
+    language: Raku
+    config:
+      list:
+        - 2022.04
+        - 2022.06
+        - 2023.06
+        - 2022.12
+    code: |
+      my @state;
+      for config()<list><> -> $v {
+        my $s = %( version => $v );
+        if "{cache_root_dir()}/{$v}_ok".IO ~~ :e {
+          $s<status> = "OK";
+        } else {
+          $s<status> = "FAIL";
+        }
+        if "{cache_root_dir()}/{$v}_time".IO ~~ :e {
+          $s<time> = "{cache_root_dir()}/{$v}_time".IO.slurp();
+        } else {
+          $s<time> = "NA";
+        }
+        @state.push: $s;
+      }
+      update_state %( list => @state );
+    init: |
+      for config()<list><> -> $v {
+        run_task("test", %( version => $v ));
+      }
+    subtasks:
+      -
+        name: test
+        language: Bash
+        init: |
+          ignore_error
+        code: |
+          set -e
+          rakubrew download moar-$version
+          rakubrew switch moar-$version
+          cd source/
+          zef install --/test --to=home .
+          export SP6_LOG_NO_TIMESTAMPS=1
+          /usr/bin/time -f "%E real,%U user,%S sys" -o "${cache_root_dir}/${version}_time" \
+          tomty  --all --show-failed --color --dump-task && \
+          touch "${cache_root_dir}/${version}_ok"
+    depends:
+      -
+        name: rakubrew-install
   -
     name: release
     if:
@@ -44,3 +102,16 @@ tasks:
       tom --clean
       fez version
       fez upload --unattended
+
+  -
+    name: rakubrew-install
+    language: Bash
+    code: |
+      set -e
+      curl -sf https://rakubrew.org/perl/rakubrew -o rakubrew
+      sudo mv rakubrew /usr/local/bin
+      sudo chmod a+x /usr/local/bin/rakubrew
+      rakubrew mode shim
+      zef install --/test Text::Table::Simple
+      sudo apk add time  --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/
+
